
# SEO settings
title: "Yusup Saepudin"
title2: "" # default: ""
description: "Banyak koding, banyak manfaat"
keywords: "belajar, koding"
url: http://yusupsaepudin.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/yusupsaepudin/yusupsaepudin.github.io
disqus_shortname: "Yusup"
twitter_username: "yusup_social"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "John Doe"
  job      : "Software Engineer"
  bio      : "1+1=3 is always TRUE in my world, a balance between binary and reality."
  thumb    : /images/author.jpg
  email    : yusupsaepudin19@gmail.com
  url      : http://yusupsaepudin.github.io
  github   : http://github.com/yusupsaepudin
  twitter  : http://twitter.com/yusup_social
  facebook : https://www.facebook.com/yusup_social
  linkedin : http://linkedin.com/in/yusup-saepudin

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@yusup_social"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
